### PR TITLE
Add ci

### LINKED ISSUE #22: Continuous Integration
In order to help you test existing functionality and avoid regressions, a test suite should be introduced. There are testing platforms available for python (i.e. nose, unittest, etc.). Once the test suite runs, the next step is to set up CI. TravisCI is free and integrated with Github for instance, there's also other alternatives which are less integrated such as buildbot.

### PR DESCRIPTION
**Pull request by IanLee1521**
I think this should work, but you should know that running tox locally I found an error with:

```
====================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'dag')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/lee1001/projs/llnl/maestrowf/.tox/py36/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/lee1001/projs/llnl/maestrowf/.tox/py36/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/lee1001/projs/llnl/maestrowf/.tox/py36/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/lee1001/projs/llnl/maestrowf/.tox/py36/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/lee1001/projs/llnl/maestrowf/.tox/py36/lib/python3.6/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/Users/lee1001/projs/llnl/maestrowf/.tox/py36/lib/python3.6/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/lee1001/projs/llnl/maestrowf/maestrowf/interfaces/__init__.py", line 32, in <module>
    from maestrowf.interfaces.script.slurmscriptadapter import SlurmScriptAdapter
  File "/Users/lee1001/projs/llnl/maestrowf/maestrowf/interfaces/script/slurmscriptadapter.py", line 38, in <module>
    from maestrowf.datastructures.core import State
  File "/Users/lee1001/projs/llnl/maestrowf/maestrowf/datastructures/__init__.py", line 43, in <module>
    from dag import DAG
ModuleNotFoundError: No module named 'dag'
```

Closes #22 when merged

### CODE REVIEW

**Comment by FrankD412** [comment]
Huh, interesting. It's been working fine on my end. I just checked this branch out locally and am going to try and reproduce it.

**Comment by IanLee1521** [comment]
```
$ git checkout add-ci
$ pip install -r requirements.txt
$ tox
```

FWIW, are you testing in python 2.7? That seems to work, but it fails in Python 3.6:

```
$ tox
...
ERROR:   py26: commands failed
  py27: commands succeeded
SKIPPED:  py32: InterpreterNotFound: python3.2
SKIPPED:  py33: InterpreterNotFound: python3.3
SKIPPED:  py34: InterpreterNotFound: python3.4
SKIPPED:  py35: InterpreterNotFound: python3.5
ERROR:   py36: commands failed
SKIPPED:  pypy: InterpreterNotFound: pypy
SKIPPED:  pypy3: InterpreterNotFound: pypy3
SKIPPED:  jython: InterpreterNotFound: jython
```

**Comment by IanLee1521** [comment]
Pretty sure you want to change ``from dag import DAG`` to ``from maestrowf.datastructures.dag import DAG`` or something close to it.

**Comment by FrankD412** [comment]
You're correct on the ```import``` statement. I found the same thing. For the interpreter errors, I've been coding primarily with python 2.7 in mind. 

python 2.6 also fails because it can't find ```OrderDict``` in ```collections```. Not sure how to fix this one in a python >= 2.7 friendly way.
python 3.6 fails because it can't find the ```yamlspecification``` module. For this one, fixing the ```import``` onion peeled to similar errors.

In any case, I'm going to make a PR for fixing the python 3.6 issue. You'll have to rebase off of that one.

**Comment by IanLee1521** [comment]
I would say we "fix it" by not supporting Python 2.6, but that's me :)

**Comment by IanLee1521** [comment]
Also, you should update your `setup.py` file with exactly what versions you are planning to support, rather than generically "2" and "3"

**Comment by FrankD412** [comment]
That's a good thought. I'll take care of that.

**Comment by FrankD412** [comment]
See PR #24 for corrections to supported Python versions.

**Comment by FrankD412** [comment]
After discussing with @IanLee1521, to avoid the ugliness of merging a PR into another PR we'll close this one to merge PR #24 into develop.

**Pull request closed without merging**
