### PR TITLE
YAMLSpecification Testing

### PR DESCRIPTION
**Pull request by kcathey**
Adding unit tests to bring up test coverage.

### CODE REVIEW

**Comment by kcathey** [comment]
@FrankD412 I'm working on some tests for YAMLSpec and wondering if this bit in [_verify_variables](https://github.com/LLNL/maestrowf/blob/4b8465a7528425b5d1ce6e40b52cc21203cf8751/maestrowf/specification/yamlspecification.py#L205-L211 ) is needed with the json schema verification, I can't get it to run the schema verification stops it before we get here.

**Comment by FrankD412** [comment]
> @FrankD412 I'm working on some tests for YAMLSpec and wondering if this bit in [_verify_variables](https://github.com/LLNL/maestrowf/blob/4b8465a7528425b5d1ce6e40b52cc21203cf8751/maestrowf/specification/yamlspecification.py#L205-L211) is needed with the json schema verification, I can't get it to run the schema verification stops it before we get here.

Ah, I hadn't thought of that. That's fair -- it might actually also get rid of the `if not value` check too since it does define valid types.

**Comment by kcathey** [comment]
> > @FrankD412 I'm working on some tests for YAMLSpec and wondering if this bit in [_verify_variables](https://github.com/LLNL/maestrowf/blob/4b8465a7528425b5d1ce6e40b52cc21203cf8751/maestrowf/specification/yamlspecification.py#L205-L211) is needed with the json schema verification, I can't get it to run the schema verification stops it before we get here.
> 
> Ah, I hadn't thought of that. That's fair -- it might actually also get rid of the `if not value` check too since it does define valid types.

The value check is actually the only piece that is actually getting processed by the _verify_variables, leaving out a value causes that ValueError to be thrown.

**Comment by kcathey** [comment]
> > @FrankD412 I'm working on some tests for YAMLSpec and wondering if this bit in [_verify_variables](https://github.com/LLNL/maestrowf/blob/4b8465a7528425b5d1ce6e40b52cc21203cf8751/maestrowf/specification/yamlspecification.py#L205-L211) is needed with the json schema verification, I can't get it to run the schema verification stops it before we get here.
> 
> Ah, I hadn't thought of that. That's fair -- it might actually also get rid of the `if not value` check too since it does define valid types.

The JSON Schema check also converts to a dict so the duplicate keys also doesn't get checked.

**Comment by kcathey** [comment]
> > > @FrankD412 I'm working on some tests for YAMLSpec and wondering if this bit in [_verify_variables](https://github.com/LLNL/maestrowf/blob/4b8465a7528425b5d1ce6e40b52cc21203cf8751/maestrowf/specification/yamlspecification.py#L205-L211) is needed with the json schema verification, I can't get it to run the schema verification stops it before we get here.
> > 
> > 
> > Ah, I hadn't thought of that. That's fair -- it might actually also get rid of the `if not value` check too since it does define valid types.
> 
> The value check is actually the only piece that is actually getting processed by the _verify_variables, leaving out a value causes that ValueError to be thrown.

And I just found a tweak to the JSON Schema that completely removes the need for `_verify_variables`

**Comment by FrankD412** [comment]
> > > > @FrankD412 I'm working on some tests for YAMLSpec and wondering if this bit in [_verify_variables](https://github.com/LLNL/maestrowf/blob/4b8465a7528425b5d1ce6e40b52cc21203cf8751/maestrowf/specification/yamlspecification.py#L205-L211) is needed with the json schema verification, I can't get it to run the schema verification stops it before we get here.
> > > 
> > > 
> > > Ah, I hadn't thought of that. That's fair -- it might actually also get rid of the `if not value` check too since it does define valid types.
> > 
> > 
> > The value check is actually the only piece that is actually getting processed by the _verify_variables, leaving out a value causes that ValueError to be thrown.
> 
> And I just found a tweak to the JSON Schema that completely removes the need for `_verify_variables`

You're just knocking things out this weekend, haha -- go ahead and throw up a PR. I'll review and test it when it goes up.

**Comment by kcathey** [comment]
> You're just knocking things out this weekend, haha -- go ahead and throw up a PR. I'll review and test it when it goes up.

Pretty much. I needed something to do on the computer that wasn't "work" and wasn't my other projects, so maestro it is :-D

**Comment by FrankD412** [comment]
> > You're just knocking things out this weekend, haha -- go ahead and throw up a PR. I'll review and test it when it goes up.
> 
> Pretty much. I needed something to do on the computer that wasn't "work" and wasn't my other projects, so maestro it is :-D

I welcome the PRs! 🎊

**Review by jsemler — APPROVED** [review]

**Review by FrankD412 — COMMENTED** [review]
I was looking through the Travis logs and saw this:
```
.tox/py35/lib/python3.5/site-packages/_pytest/junitxml.py:446
  /home/travis/build/LLNL/maestrowf/.tox/py35/lib/python3.5/site-packages/_pytest/junitxml.py:446: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0. See:
    https://docs.pytest.org/en/stable/deprecations.html#junit-family-default-value-change-to-xunit2
  for more information.
    _issue_warning_captured(deprecated.JUNIT_XML_DEFAULT_FAMILY, config.hook, 2)
```

Not that it's much of an issue, and it looks like it might just be solved when Travis builds the environment (that and it looks to just be something `tox` would have to deal with). Is that something that might break? I believe we pull have `tox = "*"` in the toml file.

**Comment by kcathey** [comment]
> I was looking through the Travis logs and saw this:
> 
> ```
> .tox/py35/lib/python3.5/site-packages/_pytest/junitxml.py:446
>   /home/travis/build/LLNL/maestrowf/.tox/py35/lib/python3.5/site-packages/_pytest/junitxml.py:446: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0. See:
>     https://docs.pytest.org/en/stable/deprecations.html#junit-family-default-value-change-to-xunit2
>   for more information.
>     _issue_warning_captured(deprecated.JUNIT_XML_DEFAULT_FAMILY, config.hook, 2)
> ```
> 
> Not that it's much of an issue, and it looks like it might just be solved when Travis builds the environment (that and it looks to just be something `tox` would have to deal with). Is that something that might break? I believe we pull have `tox = "*"` in the toml file.

This actually have to do with pytest writing out the test report xml file. The junit file format will be changing in future versions of pytest. We can fix it by changing the format in the pytest.ini.

**Comment by FrankD412** [comment]
> This actually have to do with pytest writing out the test report xml file. The junit file format will be changing in future versions of pytest. We can fix it by changing the format in the pytest.ini.

Got it -- yeah, that's what it looked like. Just wanted to verify.

**Review by FrankD412 — APPROVED** [review]

**Pull request merged**
