### PR TITLE
Feature/crkrenn/multidimensional sampling

### PR DESCRIPTION
**Pull request by crkrenn**
I've implemented three "NTNF" style sampling interfaces. 

Because this is of general interest and can be implemented in maestro alone, I am submitting it here. 

Best_candidate sampling is next.

### CODE REVIEW

**Comment by crkrenn** [comment]
This pull request reemphasizes my interest in passing maestro options via the yaml file. Then, we can type `maestro run spec` instead of `maestro run spec --pgen {{one_of_my_pgen_files_I_can_not_remember_which_one}} --autoyes`

Pretty please?

```
AUTOYES: True
PGEN: ./pgen_sample.py
```

**Comment by FrankD412** [comment]
I'm wondering if these don't belong in samples -- I'm thinking they might either belong in documentation or in a folder on their own. @jwhite242 is writing some pgen documentation, might it belong there?

**Comment by FrankD412** [comment]
> This pull request reemphasizes my interest in passing maestro options via the yaml file. Then, we can type `maestro run spec` instead of `maestro run spec --pgen {{one_of_my_pgen_files_I_can_not_remember_which_one}} --autoyes`
> 
> Pretty please?
> 
> ```
> AUTOYES: True
> PGEN: ./pgen_sample.py
> ```

So, I've been considering a different but it doesn't feel right to place those settings into the specification itself. They are not required to actually run the study, and are optional. I've been tossing around the idea of using a smaller spec that could list specs with their command line options. A sort of `maestro play` feature. You could then spin off multiple studies.

**Comment by crkrenn** [comment]
@FrankD412 & @jsemler, what do you think of a `maestro_config.yaml` file like the one that Brian D. has been talking about in his work with Jessica?

**Comment by crkrenn** [comment]
@FrankD412 (cc @jsemler), I want to help you keep your code base clean and maintainable. I'd also like a place to hang my sampling code, and associating it with maestro seems to be the right choice because it only depends on maestro (and some public third-party packages). 

Could a `third-party` directory or LLNL/maestro-examples repo be appropriate? 

See the following links for precedent: 

https://github.com/gramps-project
https://www.gramps-project.org/wiki/index.php/Addons_development

**Comment by FrankD412** [comment]
@crkrenn -- I've been meaning to collaborate with users on an example directory. These might be a good start there, I also think they might be good here for advanced documentation. I'm feeling 50/50 on it  -- @jwhite242 @jsemler, thoughts?

**Comment by crkrenn** [comment]
Frank,

I don’t think my examples add much to the understanding of writing pgen.py scripts. Your monte-carlo example does a good job there.

But, I do think that my examples are something that teams at LLNL would build on, and perhaps elsewhere as well.

V/r,

-Chris


Chris Krenn
Lawrence Livermore National Laboratory
Krenn1@llnl.gov<mailto:Krenn1@llnl.gov>
925-423-8636
--------------------------------------------
Q: Why is this email [hopefully] five sentences or less?
A: http://five.sentenc.es

**Comment by FrankD412** [comment]
@ckrenn -- Makes sense. I will look into what's needed to start a new repository of examples and get back to you. In the mean time we can keep this PR open to keep track. Thanks!

**Comment by FrankD412** [comment]
@crkrenn -- I've started an example repository. Please submit a PR to the collection of examples [here](https://github.com/LLNL/maestro_sheetmusic).

**Comment by FrankD412** [comment]
@crkrenn -- do you mind if I close this PR and the other sampling PR since they're now up on the sheetmusic repository?

**Pull request closed without merging**
