### PR TITLE
Flux Adapter Clean up and Addition of Job Priority

### PR DESCRIPTION
**Pull request by FrankD412**
This PR cleans up some things and adds to the `FluxScriptAdapter`:
+ Renamed `use_broker` in the YAML specification to `nested` to better match with Flux's externally used terminology.
+ Addition of `urgency` to the YAML specification for job priority.
+ A fix for `inf` wall time for the `FluxScriptAdapter` that previously caused an exception when dealing with string based digits.

### CODE REVIEW

**Comment by FrankD412** [comment]
@jmast -- how's this looking?

**Comment by Jmast** [comment]
So far no issues. I haven't tried the AHA pipeline yet (waiting on
Xiaohua), but I suspect it will be fine as long as the WALL_TIME changes
work. I forget what we had issues with related to 0, inf, etc.
-- Jeff

**Comment by FrankD412** [comment]
@Jmast -- I believe that it was that `inf` was not accepted. I believe that it should work now, and it did the last I tested it. But that's different than in the wild.

**Comment by FrankD412** [comment]
@Jmast -- mind if I go ahead and merge this? I can rebase your PerfFlow branch and we can handle any bugs in another PR. Does that sound good?

**Comment by Jmast** [comment]
Yes, however, there is still one outstanding problem I run into related to
fluxscriptadpter doing cores_per_task validation. Here is a diff of what I
had to change:

diff --git a/maestrowf/interfaces/script/fluxscriptadapter.py
b/maestrowf/inter
index 6b58ec8..c7bfbd7 100644
--- a/maestrowf/interfaces/script/fluxscriptadapter.py
+++ b/maestrowf/interfaces/script/fluxscriptadapter.py
@@ -209,11 +209,11 @@ class FluxScriptAdapter(SchedulerScriptAdapter):
         ncores = cores_per_task * nodes
         # Check to make sure that cores_per_task matches if processors
         # is specified.
-        if processors > 0 and processors > ncores:
-            msg = "Calculated ncores (nodes * cores per task) = {} " \
-                  "-- procs = {}".format(ncores, processors)
-            LOGGER.error(msg)
-            raise ValueError(msg)
+        ## if processors > 0 and processors > ncores:
+        ##    msg = "Calculated ncores (nodes * cores per task) = {} " \
+        ##          "-- procs = {}".format(ncores, processors)
+        ##    LOGGER.error(msg)
+        ##    raise ValueError(msg)

         # Raise an exception if ncores is 0
         if ncores <= 0:

-- Jeff

**Comment by FrankD412** [comment]
@Jmast -- I've added your change, sorry it took so long. Let me know if you've found any other issues. There's also the PerfFlow Aspect branch. I need to go check, but I think there's now an environment variable that can turn off profiling but I need to verify. I can rebase that branch on the new main branch once it's merged in if you still needed it.

**Pull request merged**
