### PR TITLE
Makefile cleanup

### PR DESCRIPTION
**Pull request by FrankD412**
This pull request handles the makefile clean up specified in issue #7

### CODE REVIEW

**Comment by FrankD412** [comment]
It should, though it's not producing a lot (if any) documentation currently.

**Comment by FrankD412** [comment]
@IanLee1521 -- Did you end up testing the make docs?

**Comment by IanLee1521** [comment]
Yes, and at least something is wrong:

```
lee1001 at andromeda in [~/projs/llnl/maestrowf] git:(makefile_cleanup)
10:16:20 (maestrowf) > make docs
make: `docs' is up to date.
```

**Comment by FrankD412** [comment]
Corrected the issue. Ready for review again.

**Pull request merged**
